---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-public
  namespace: jenkins
spec:
  type: NodePort
  ports:
  - name: jenkins-public
    port: 8080
    nodePort: 32000
  selector:
    app: jenkins